### ISSUE TITLE
flockerctl installation 

### ISSUE THREAD

**Issue by Coyzz** [ScatterHQ/flocker#3]
when i try to download the installation : 

manager01:~$ sudo curl -sSL https://get.flocker.io | sh
sh: 3: Syntax error: newline unexpected

manager01:~$ sudo curl -sSL https://get.flocker.io

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 first byte timeout</title>
  </head>
  <body>
    <h1>Error 503 first byte timeout</h1>
    <p>first byte timeout</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-ams4128-AMS 1484325222 2705976644</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

**Comment by tomprince** [comment]
It looks like this is hosted by github, which is [currently](https://status.github.com/).

**Comment by tomprince** [comment]
This appears to be available again.
